apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hdx-oss.fullname" . }}-app
  labels:
    {{- include "hdx-oss.labels" . | nindent 4 }}
    app: {{ include "hdx-oss.fullname" . }}
    {{- if .Values.hyperdx.labels }}
    {{- with .Values.hyperdx.labels }}
    {{- toYaml . | nindent 4 }} 
    {{- end -}}
    {{- end }}
spec:
  replicas: {{ .Values.hyperdx.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "hdx-oss.selectorLabels" . | nindent 6 }}
      app: {{ include "hdx-oss.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "hdx-oss.selectorLabels" . | nindent 8 }}
        app: {{ include "hdx-oss.fullname" . }}
      annotations:
      {{- if .Values.hyperdx.annotations }}
        {{- with .Values.hyperdx.annotations }}
        {{- toYaml . | nindent 8 }} 
        {{- end -}}
      {{- end }}
    spec:
      {{- if .Values.hyperdx.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.hyperdx.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.hyperdx.tolerations }}
      tolerations:
        {{- toYaml .Values.hyperdx.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.hyperdx.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.hyperdx.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if .Values.hyperdx.priorityClassName }}
      priorityClassName: {{ .Values.hyperdx.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.mongodb.enabled }}
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ include "hdx-oss.fullname" . }}-mongodb {{ .Values.mongodb.port }}; do echo waiting for mongodb; sleep 2; done;']
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.hyperdx.image.repository }}:{{ .Values.hyperdx.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.hyperdx.image.pullPolicy }}
          ports:
            - name: app-port
              containerPort: {{ .Values.hyperdx.appPort }}
            - name: api-port
              containerPort: {{ .Values.hyperdx.apiPort }}
            - name: opamp-port
              containerPort: {{ .Values.hyperdx.opampPort }}
          {{- if .Values.hyperdx.resources }}
          resources:
            {{- toYaml .Values.hyperdx.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.hyperdx.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.hyperdx.apiPort }}
            initialDelaySeconds: {{ .Values.hyperdx.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.hyperdx.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.hyperdx.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.hyperdx.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.hyperdx.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.hyperdx.apiPort }}
            initialDelaySeconds: {{ .Values.hyperdx.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.hyperdx.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.hyperdx.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.hyperdx.readinessProbe.failureThreshold }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "hdx-oss.fullname" . }}-app-config
          env:
            - name: HYPERDX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "hdx-oss.fullname" . }}-app-secrets
                  key: api-key
            {{- if .Values.hyperdx.defaultConnections }}
            - name: DEFAULT_CONNECTIONS
              value: {{ tpl .Values.hyperdx.defaultConnections . | quote }}
            {{- end }}
            {{- if .Values.hyperdx.defaultSources }}
            - name: DEFAULT_SOURCES
              value: {{ tpl .Values.hyperdx.defaultSources . | quote }}
            {{- end }}
            {{- with .Values.hyperdx.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
